server:
  port: 9000
  servlet:
    session:
      timeout: 10s
      cookie:
        http-only: true
        secure: false

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://39.108.164.17:3306/devicedb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: kakarot
    password: A1411050104a*
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    cache: false # 缓存配置 开发阶段应该配置为false 因为经常会改
    suffix: .html # 模版后缀名 默认为ftl
    charset: UTF-8 # 文件编码
    template-loader-path: classpath:/templates/
  application:
    name: cloud-auth-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848


#logging:
#    config: classpath:log4j2-dev.xml

mybatis:
    configuration:
      mapUnderscoreToCamelCase: true